NAME: webhook
LAST DEPLOYED: Thu Nov 28 19:37:19 2024
NAMESPACE: leonardo-bdaas-akson
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: example-webhook/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-example-webhook
  namespace: "leonardo-bdaas-akson"
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
---
# Source: example-webhook/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-example-webhook:domain-solver
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
rules:
  - apiGroups:
      - acme.mycompany.com
    resources:
      - '*'
    verbs:
      - 'create'
---
# Source: example-webhook/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-example-webhook:auth-delegator
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: webhook-example-webhook
    namespace: leonardo-bdaas-akson
---
# Source: example-webhook/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-example-webhook:domain-solver
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-example-webhook:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Source: example-webhook/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook-example-webhook:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: webhook-example-webhook
    namespace: leonardo-bdaas-akson
---
# Source: example-webhook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: webhook-example-webhook
  namespace: "leonardo-bdaas-akson"
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: example-webhook
    release: webhook
---
# Source: example-webhook/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-example-webhook
  namespace: "leonardo-bdaas-akson"
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app: example-webhook
      release: webhook
  template:
    metadata:
      labels:
        app: example-webhook
        release: webhook
    spec:
      serviceAccountName: webhook-example-webhook
      containers:
        - name: example-webhook
          image: "mycompany/webhook-image:latest"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "acme.mycompany.com"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: webhook-example-webhook-webhook-tls
---
# Source: example-webhook/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.mycompany.com
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "leonardo-bdaas-akson/webhook-example-webhook-webhook-tls"
spec:
  group: acme.mycompany.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: webhook-example-webhook
    namespace: leonardo-bdaas-akson
  version: v1alpha1
---
# Source: example-webhook/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-example-webhook-ca
  namespace: "leonardo-bdaas-akson"
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
spec:
  secretName: webhook-example-webhook-ca
  duration: 43800h # 5y
  issuerRef:
    name: webhook-example-webhook-selfsign
  commonName: "ca.example-webhook.cert-manager"
  isCA: true
---
# Source: example-webhook/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-example-webhook-webhook-tls
  namespace: "leonardo-bdaas-akson"
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
spec:
  secretName: webhook-example-webhook-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: webhook-example-webhook-ca
  dnsNames:
  - webhook-example-webhook
  - webhook-example-webhook.leonardo-bdaas-akson
  - webhook-example-webhook.leonardo-bdaas-akson.svc
---
# Source: example-webhook/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-example-webhook-selfsign
  namespace: "leonardo-bdaas-akson"
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: example-webhook/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-example-webhook-ca
  namespace: "leonardo-bdaas-akson"
  labels:
    app: example-webhook
    chart: example-webhook-0.1.0
    release: webhook
    heritage: Helm
spec:
  ca:
    secretName: webhook-example-webhook-ca

